In [1]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


In [2]:
# Loading the dataset
df = pd.read_csv(r'D:\ExcelR\Project\DataScience_Project\Titanic survivors logistic regression\Titanic-Dataset.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
# To drop unwanted columns and save the data as the original dataset. 
df = df.drop(['PassengerId','Name','Ticket'],axis=1)
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [4]:
# To check the type of data and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object 
 8   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [5]:
# To get the total null values
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [6]:
# To get the percnetage of null values
df.isnull().sum()/len(df)*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [7]:
# Dropping the Cabin column as most of its values are null.
df = df.drop(['Cabin'],axis = 1)

In [8]:
# To fill the null values
# Here we take mean first to fill the null values in Age, but since it did not perform well in training and testing so we use the median instead.

df['Age'] = df['Age'].fillna(round(df['Age'].median()))

In [9]:
# To get the count of each element in the Embarked data.
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [10]:
# To fill the null values in the Embarked data with the mode element.
df['Embarked'] = df['Embarked'].fillna('S')

In [11]:
# To check the percentage of remaining null values after filling the Embarked data with the mode element.
df.isnull().sum()/len(df)*100

Survived    0.0
Pclass      0.0
Sex         0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
Embarked    0.0
dtype: float64

In [12]:
# To convert the textual data in the Sex and Embarked columns using feature encoding (here we use One Hot Encoding).
df = pd.get_dummies(data=df,columns=['Sex','Embarked'],dtype=int,drop_first=True)
df

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
0           0       3  22.0      1      0   7.2500         1           0   
1           1       1  38.0      1      0  71.2833         0           0   
2           1       3  26.0      0      0   7.9250         0           0   
3           1       1  35.0      1      0  53.1000         0           0   
4           0       3  35.0      0      0   8.0500         1           0   
..        ...     ...   ...    ...    ...      ...       ...         ...   
886         0       2  27.0      0      0  13.0000         1           0   
887         1       1  19.0      0      0  30.0000         0           0   
888         0       3  28.0      1      2  23.4500         0           0   
889         1       1  26.0      0      0  30.0000         1           0   
890         0       3  32.0      0      0   7.7500         1           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 9 columns]

In [13]:
# Assigning x_data and y_data
x = df.drop(['Survived'],axis=1)
y = df['Survived']

In [14]:
x

Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0         3  22.0      1      0   7.2500         1           0           1
1         1  38.0      1      0  71.2833         0           0           0
2         3  26.0      0      0   7.9250         0           0           1
3         1  35.0      1      0  53.1000         0           0           1
4         3  35.0      0      0   8.0500         1           0           1
..      ...   ...    ...    ...      ...       ...         ...         ...
886       2  27.0      0      0  13.0000         1           0           1
887       1  19.0      0      0  30.0000         0           0           1
888       3  28.0      1      2  23.4500         0           0           1
889       1  26.0      0      0  30.0000         1           0           0
890       3  32.0      0      0   7.7500         1           1           0

[891 rows x 8 columns]

In [15]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [17]:
# To spit the data into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [18]:
x_train

Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
414       3  44.0      0      0    7.9250         1           0           1
777       3   5.0      0      0   12.4750         0           0           1
524       3  28.0      0      0    7.2292         1           0           0
267       3  25.0      1      0    7.7750         1           0           1
743       3  24.0      1      0   16.1000         1           0           1
..      ...   ...    ...    ...       ...       ...         ...         ...
438       1  64.0      1      4  263.0000         1           0           1
664       3  20.0      1      0    7.9250         1           0           1
400       3  39.0      0      0    7.9250         1           0           1
68        3  17.0      4      2    7.9250         0           0           1
436       3  21.0      2      2   34.3750         0           0           1

[712 rows x 8 columns]

In [20]:
x_test

Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
590       3  35.0      0      0    7.1250         1           0           1
301       3  28.0      2      0   23.2500         1           1           0
115       3  21.0      0      0    7.9250         1           0           1
30        1  40.0      0      0   27.7208         1           0           0
757       2  18.0      0      0   11.5000         1           0           1
..      ...   ...    ...    ...       ...       ...         ...         ...
93        3  26.0      1      2   20.5750         1           0           1
152       3  55.5      0      0    8.0500         1           0           1
377       1  27.0      0      2  211.5000         1           0           0
647       1  56.0      0      0   35.5000         1           0           0
586       2  47.0      0      0   15.0000         1           0           1

[179 rows x 8 columns]

In [23]:
y_train

414    1
777    1
524    0
267    1
743    0
      ..
438    0
664    1
400    1
68     1
436    0
Name: Survived, Length: 712, dtype: int64

In [26]:
y_test

590    0
301    1
115    0
30     0
757    0
      ..
93     0
152    0
377    0
647    1
586    0
Name: Survived, Length: 179, dtype: int64

In [41]:
# To get the shape of the training and testing data.
x_train.shape

(712, 8)

In [43]:
x_test.shape

(179, 8)

In [45]:
len(y_train)

712

In [47]:
len(y_test)

179

In [49]:
# Assigning logisticRegression to a variable
lr = LogisticRegression()
lr

LogisticRegression()

In [51]:
# To fit the data in LR
lr.fit(x_train,y_train)

C:\Users\91808\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [53]:
# To get the m value or coefficient
lr.coef_

array([[-1.10662555, -0.03609134, -0.31477655, -0.04718234,  0.00275738,
        -2.42856998,  0.21051426, -0.24908317]])

In [55]:
# To get the intercept
lr.intercept_

array([4.82249477])

In [57]:
# To get the predicted y_train and y_test
y_pred_train = lr.predict(x_train)
y_pred_test = lr.predict(x_test)

In [59]:
y_pred_train

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,

In [61]:
y_pred_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0], dtype=int64)

In [63]:
# To get the classification report including accuracy, precision, recall, and F1-score for the training data.
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       429
           1       0.75      0.72      0.73       283

    accuracy                           0.79       712
   macro avg       0.78      0.78      0.78       712
weighted avg       0.79      0.79      0.79       712



In [65]:
# To get the classification report including accuracy, precision, recall, and F1-score for the training data.
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       120
           1       0.74      0.71      0.72        59

    accuracy                           0.82       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.82      0.82      0.82       179



In [67]:
# To get the column names
x.columns

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [69]:
df

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
0           0       3  22.0      1      0   7.2500         1           0   
1           1       1  38.0      1      0  71.2833         0           0   
2           1       3  26.0      0      0   7.9250         0           0   
3           1       1  35.0      1      0  53.1000         0           0   
4           0       3  35.0      0      0   8.0500         1           0   
..        ...     ...   ...    ...    ...      ...       ...         ...   
886         0       2  27.0      0      0  13.0000         1           0   
887         1       1  19.0      0      0  30.0000         0           0   
888         0       3  28.0      1      2  23.4500         0           0   
889         1       1  26.0      0      0  30.0000         1           0   
890         0       3  32.0      0      0   7.7500         1           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 9 columns]

In [71]:
# To get input from the user

for i in range(2):
    Pclass = int(input('Enter your Class selection :'))
    Age = int(input('Enter your Age :'))
    SibSp = int(input('Enter your number of Siblings or Spouse :'))
    Parch = int(input('Enter your number of Parents or Childrens :'))
    Fare = float(input('Enter your Fare:'))
    Sex = input('Enter your Sex [M/F] :').upper()
    Embarked_Q = input('Enter if you Embarked from Queenstown[Y/N] :').upper()
    Embarked_S = input('Enter if you Embarked from Southhampton[Y/N] :').upper()

    if Sex == 'M':
        Sex = 1
    else:
        Sex = 0

    if Embarked_Q == 'Y':
        Embarked_Q = 1
    else:
        Embarked_Q = 0

    if Embarked_S == 'Y':
        Embarked_S = 1
    else:
        Embarked_S = 0

    user_input = np.array([Pclass,Age,SibSp,Parch,Fare,Sex,Embarked_Q,Embarked_S]).reshape(1,-1)
    prediction = lr.predict(user_input)
    if prediction == 0:
         print("RIP! , You will not Survive")
    else:
        print("Hooray! , You will Survive")

Enter your Class selection : 2
Enter your Age : 30
Enter your number of Siblings or Spouse : 0
Enter your number of Parents or Childrens : 1
Enter your Fare: 20
Enter your Sex [M/F] : m
Enter if you Embarked from Queenstown[Y/N] : y
Enter if you Embarked from Southhampton[Y/N] : n


C:\Users\91808\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


RIP! , You will not Survive


Enter your Class selection : 1
Enter your Age : 45
Enter your number of Siblings or Spouse : 0
Enter your number of Parents or Childrens : 1
Enter your Fare: 72.3
Enter your Sex [M/F] : f
Enter if you Embarked from Queenstown[Y/N] : n
Enter if you Embarked from Southhampton[Y/N] : y


Hooray! , You will Survive


C:\Users\91808\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
